const API_BASE = "https://ipl-okn0.onrender.com";
const fixturesList = document.getElementById("fixturesList");
const featuredCard = document.getElementById("featuredMatchCard");
let allMatches = [];
let currentFilter = "upcoming";

const TEAM_CODES = { "Mumbai Indians":"MI", "Chennai Super Kings":"CSK", "Royal Challengers Bengaluru":"RCB", "Royal Challengers Bangalore":"RCB", "Kolkata Knight Riders":"KKR", "Delhi Capitals":"DC", "Sunrisers Hyderabad":"SRH", "Rajasthan Royals":"RR", "Punjab Kings":"PBKS", "Lucknow Super Giants":"LSG", "Gujarat Titans":"GT" };
function escapeHtml(value) { return String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function team(value) { return typeof value === "object" ? (value?.name || value?.team || "Opponent") : String(value || "Opponent"); }
function getTeams(match) { const a=team(match.team1||match.teamA||match.homeTeam||match.teams?.[0]); const b=team(match.team2||match.teamB||match.awayTeam||match.teams?.[1]); return a.toLowerCase().includes("mumbai") ? {mi:a,opponent:b} : {mi:b,opponent:a}; }
function dateValue(match) { return match.date||match.matchDate||match.startDate||match.start_time||""; }
function timestamp(match) { const t=new Date(dateValue(match)).getTime(); return Number.isFinite(t) ? t : Number.MAX_SAFE_INTEGER; }
function formatDate(value) { const d=new Date(value); return Number.isNaN(d.getTime()) ? "Date TBA" : d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}); }
function shortCode(name) { const key=String(name||"").trim(); return TEAM_CODES[key] || Object.keys(TEAM_CODES).find(k=>k.toLowerCase()===key.toLowerCase())?.replace(/^.*$/,(x)=>TEAM_CODES[x]) || key.split(/\s+/).map(x=>x[0]).join("").slice(0,4).toUpperCase() || "TBA"; }
function isCompleted(match) { const status=String(match.status||match.matchStatus||match.result||"").toLowerCase(); if(/won|lost|draw|tie|completed|finished|result/.test(status)) return true; const t=timestamp(match); return Number.isFinite(t)&&t<Date.now(); }
function filteredMatches() { return currentFilter === "results" ? allMatches.filter(isCompleted) : currentFilter === "upcoming" ? allMatches.filter(m=>!isCompleted(m)) : allMatches; }
function showMessage(message) { fixturesList.innerHTML=`<div class="api-message"><i class="fa-solid fa-circle-info"></i><p>${escapeHtml(message)}</p><a class="secondary-btn" href="tickets.html">Open Tickets</a></div>`; }
function renderFeatured(match) { const {mi,opponent}=getTeams(match); const date=dateValue(match),time=match.time||match.matchTime||"Time TBA",venue=match.venue||match.stadium||"Venue TBA",id=match.id??match.match_id??match.matchId; document.getElementById("featuredMI").textContent=mi; document.getElementById("featuredOpponent").textContent=opponent; document.getElementById("featuredOpponentShort").textContent=shortCode(opponent); document.getElementById("featuredDate").textContent=formatDate(date); document.getElementById("featuredTime").textContent=time; document.getElementById("featuredVenue").textContent=venue; document.getElementById("featuredStatus").innerHTML=`<i class="fa-solid fa-circle"></i> ${isCompleted(match)?"RESULT":"NEXT MATCH"}`; document.getElementById("featuredVsStatus").textContent=isCompleted(match)?"COMPLETED":"UPCOMING"; const btn=document.getElementById("featuredBookingBtn"); btn.href=id!=null&&!isCompleted(match)?`booking.html?match_id=${encodeURIComponent(id)}`:"tickets.html"; btn.innerHTML=`<i class="fa-solid fa-ticket"></i> ${isCompleted(match)?"View Tickets":"Book Tickets"}`; }
function renderFixtures(matches) { fixturesList.innerHTML=""; matches.forEach(match=>{ const {mi,opponent}=getTeams(match),date=dateValue(match),time=match.time||match.matchTime||"Time TBA",venue=match.venue||match.stadium||"Venue TBA",id=match.id??match.match_id??match.matchId,completed=isCompleted(match); const card=document.createElement("article"); card.className="fixture-card"; card.innerHTML=`<div class="fixture-date"><span>DATE</span><strong>${escapeHtml(new Date(date).toLocaleDateString("en-IN",{day:"2-digit",month:"short"})||"TBA")}</strong><small>${escapeHtml(new Date(date).getFullYear()||"2026")}</small></div><div class="fixture-teams"><div><img src="images/logo.png" alt="Mumbai Indians"><span>${escapeHtml(mi)}</span></div><b>VS</b><div><div class="fixture-opponent"><span>${escapeHtml(shortCode(opponent))}</span></div><span>${escapeHtml(opponent)}</span></div></div><div class="fixture-info"><p><i class="fa-solid fa-location-dot"></i> ${escapeHtml(venue)}</p><p><i class="fa-regular fa-clock"></i> ${escapeHtml(time)}</p></div><div class="fixture-actions">${!completed&&id!=null?`<a href="booking.html?match_id=${encodeURIComponent(id)}" class="ticket-btn"><i class="fa-solid fa-ticket"></i> Book Tickets</a>`:`<a href="tickets.html" class="ticket-btn">${completed?"Match Completed":"Tickets TBA"}</a>`}<a href="match-details.html?match_id=${encodeURIComponent(id??"")}" class="details-btn">Match Details <i class="fa-solid fa-arrow-right"></i></a></div>`; fixturesList.appendChild(card); }); }
function renderCurrentFilter() { const list=filteredMatches(); if(!list.length){ showMessage(currentFilter==="results"?"No completed Mumbai Indians matches found.":"No upcoming Mumbai Indians matches found."); return; } renderFixtures(list); }
async function loadMatches() { try { fixturesList.innerHTML='<div class="api-message"><i class="fa-solid fa-spinner fa-spin"></i><p>Loading Mumbai Indians fixtures...</p></div>'; const response=await fetch(`${API_BASE}/ipl-2026-schedule`,{cache:"no-store"}); if(!response.ok) throw new Error(); const data=await response.json(); allMatches=(Array.isArray(data)?data:data.matches||data.data||[]).filter(m=>getTeams(m).mi.toLowerCase().includes("mumbai")).sort((a,b)=>timestamp(a)-timestamp(b)); if(!allMatches.length) throw new Error(); const next=allMatches.find(m=>!isCompleted(m))||allMatches[0]; renderFeatured(next); renderCurrentFilter(); } catch(error) { console.error(error); showMessage("Match schedule is temporarily unavailable. Visit Tickets for the latest booking options."); } }
document.querySelectorAll(".match-tab").forEach(tab=>tab.addEventListener("click",()=>{currentFilter=tab.dataset.filter||"upcoming";document.querySelectorAll(".match-tab").forEach(t=>t.classList.toggle("active",t===tab));if(allMatches.length)renderCurrentFilter();}));
loadMatches();
