const FALLBACK_IMAGE="https://www.mumbaiindians.com/static-assets/waf-images/c7/6e/c1/16-9/592-444/DAtzKSYFre.jpg";
const PLAYER_IMAGES={"hardik pandya":63751,"am ghazanfar":96648,"ashwani kumar":74296,"atharva ankolekar":68585,"corbin bosch":63605,"danish malewar":89179,"deepak chahar":59547,"jasprit bumrah":63755,"keshav maharaj":48607,"krish bhagat":88262,"mahipal lomror":65432,"mayank markande":67126,"mayank rawat":66974,"mitchell santner":57903,"mohammad izhar":137547,"naman dhir":100353,"raghu sharma":67726,"robin minz":95322,"rohit sharma":3852,"ruchit ahir":94913,"ryan rickelton":64941,"shardul thakur":63345,"sherfane rutherford":67285,"suryakumar yadav":11803,"tilak varma":70761,"trent boult":4338,"will jacks":66927};
const FALLBACK_SQUAD=[
["Hardik Pandya","All-Rounder","India","33"],["Rohit Sharma","Batter","India","45"],["Suryakumar Yadav","Batter","India","63"],["Tilak Varma","Batter","India","9"],["Ruchit Ahir","Batter","India",""],["Danish Malewar","Batter","India",""],["Ryan Rickelton","Wicket Keeper","South Africa","19"],["Robin Minz","Wicket Keeper","India",""],["Jasprit Bumrah","Bowler","India","93"],["Trent Boult","Bowler","New Zealand","18"],["Deepak Chahar","Bowler","India","90"],["AM Ghazanfar","Bowler","Afghanistan",""],["Ashwani Kumar","Bowler","India",""],["Keshav Maharaj","Bowler","South Africa",""],["Mayank Markande","Bowler","India",""],["Raghu Sharma","Bowler","India",""],["Mohammad Izhar","Bowler","India",""],["Corbin Bosch","All-Rounder","South Africa",""],["Will Jacks","All-Rounder","England",""],["Mitchell Santner","All-Rounder","New Zealand",""],["Naman Dhir","All-Rounder","India",""],["Shardul Thakur","All-Rounder","India",""],["Mahipal Lomror","All-Rounder","India",""],["Mayank Rawat","All-Rounder","India",""],["Krish Bhagat","All-Rounder","India",""],["Atharva Ankolekar","All-Rounder","India",""],["Sherfane Rutherford","Batter","West Indies",""]
].map(([name,role,country,jersey])=>({name,role,country,jersey}));
const squadContainer=document.getElementById("squadContainer");const squadStatus=document.getElementById("squadStatus");
function normalizeName(v){return String(v||"").trim().toLowerCase().replace(/\s+/g," ")}
function escapeHTML(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function getName(p){return p?.name||p?.Name||p?.player_name||p?.full_name||p?.playerName||""}
function getRole(p){return p?.role||p?.Role||p?.type||p?.player_role||p?.playerRole||"Player"}
function getCountry(p){return p?.country||p?.Country||p?.nationality||p?.Nationality||p?.nation||"India"}
function getJersey(p){return p?.jersey||p?.jersey_number||p?.jerseyNumber||p?.number||p?.Jersey||""}
function getImage(name){const id=PLAYER_IMAGES[normalizeName(name)];return id?`https://www.mumbaiindians.com/static-assets/images/players/large/action-shots/${id}.png?v=4.16&w=400`:FALLBACK_IMAGE}
function countryCode(c){const map={India:"IND",England:"ENG",Australia:"AUS","New Zealand":"NZ","South Africa":"SA",Afghanistan:"AFG","West Indies":"WI"};return map[c]||String(c||"India").slice(0,3).toUpperCase()}
function category(p){const r=getRole(p).toLowerCase();if(r.includes("wicket")||r.includes("keeper"))return"WICKET KEEPERS";if(r.includes("all-round")||r.includes("allround")||r.includes("all round"))return"ALL-ROUNDERS";if(r.includes("bowl")||r.includes("spinner")||r.includes("pace"))return"BOWLERS";return"BATTERS"}
function displayRole(p){const c=category(p);return c==="WICKET KEEPERS"?"WICKET KEEPER":c==="ALL-ROUNDERS"?"ALL-ROUNDER":c==="BOWLERS"?"BOWLER":"BATTER"}
function renderCaptain(){const captain=FALLBACK_SQUAD[0],image=document.getElementById("captainImage");document.getElementById("captainName").textContent=captain.name.toUpperCase();document.getElementById("captainJersey").textContent=captain.jersey||"33";document.getElementById("captainRole").textContent="AR";document.getElementById("captainCountry").textContent=countryCode(captain.country);image.src=getImage(captain.name);image.alt=captain.name;image.onerror=()=>{image.src=FALLBACK_IMAGE}}
function renderSquad(players){const groups={"BATTERS":[],"WICKET KEEPERS":[],"ALL-ROUNDERS":[],"BOWLERS":[]};players.forEach(p=>groups[category(p)].push(p));squadContainer.innerHTML="";Object.entries(groups).forEach(([title,group])=>{if(!group.length)return;const section=document.createElement("section");section.className="squad-section dynamic-squad-group";section.innerHTML=`<div class="squad-heading"><p class="section-tag">THE BLUE ARMY</p><h2>${title}</h2></div>`;const grid=document.createElement("div");grid.className="players-grid";group.forEach(p=>{const name=getName(p),card=document.createElement("article");card.className="player-card";card.innerHTML=`<div class="player-image"><img src="${escapeHTML(getImage(name))}" alt="${escapeHTML(name)}" loading="lazy"><span class="jersey-number">${escapeHTML(getJersey(p)||"")}</span></div><div class="player-info"><h3>${escapeHTML(name).toUpperCase()}</h3><p>${escapeHTML(displayRole(p))} • ${escapeHTML(countryCode(getCountry(p)))}</p></div>`;card.querySelector("img").onerror=e=>{e.currentTarget.src=FALLBACK_IMAGE};grid.appendChild(card)});section.appendChild(grid);squadContainer.appendChild(section)})}
async function loadSquad(){if(!squadContainer)return;squadStatus.textContent="Loading Mumbai Indians squad...";try{const response=await fetch("https://ipl-okn0.onrender.com/squad/mi",{cache:"no-store"});if(response.ok){const data=await response.json();const apiPlayers=Array.isArray(data?.players)?data.players:Array.isArray(data?.data)?data.data:Array.isArray(data)?data:[];const known=apiPlayers.filter(p=>PLAYER_IMAGES[normalizeName(getName(p))]);if(known.length>=10){const byName=new Map(known.map(p=>[normalizeName(getName(p)),p]));const merged=FALLBACK_SQUAD.map(p=>({...p,...(byName.get(normalizeName(p.name))||{})}));renderCaptain();renderSquad(merged);squadStatus.style.display="none";return}}}catch(error){console.warn("Squad API unavailable; using verified MI roster",error)}renderCaptain();renderSquad(FALLBACK_SQUAD);squadStatus.style.display="none"}
loadSquad();
